### PR TITLE
Improved typings

### PR DESCRIPTION
**Pull request by jvorcak**

### CODE REVIEW

**Comment by S4n60w3n** [comment]
ah it is a WIP, ok.... Looks good tho, i like it

**Comment by S4n60w3n** [comment]
@jvorcak Build has failed

**Comment by jvorcak** [comment]
> @jvorcak Build has failed

I'm aware, I need to fix more type issues, but I don't have time for it right now. I'll fix asap

**Comment by jvorcak** [comment]
> IMHO - Looks good, finally it looks more like typescript :D

Far away from Typescript, but it's better than nothing :)

**Comment by jvorcak** [comment]
@S4n60w3n can you please resolve conflicts and merge?

**Pull request merged**
